language: shell
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - valgrind

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew install valgrind ; fi

script: time sh ./tests/check-suppressions-syntax
